/**
 * Writing an edited timeline back into an authored scenario file.
 *
 * The editor owns the notes and nothing else. Everything around them — asset
 * bindings, class parameters, the prose a designer wrote about a level — is
 * carried through untouched, because it is somebody's authored content and an
 * editor that rewrote it while moving a note would be a data-loss bug with a
 * friendly face.
 *
 * Three things are *derived* rather than carried, because they are statements
 * about the notes and the notes just changed:
 *
 *   - `noteOpportunityCount`, which `load.ts` checks against the prompt;
 *   - the star thresholds, which are a fixed ladder over that count;
 *   - the minigame's own level data, which only the minigame can fix
 *     ({@link MinigameAuthoring}).
 */

import {
  ATTEMPT_REPEATS,
  BEATS_PER_MEASURE,
  JUDGMENT_POINTS,
  PHRASE_BEATS,
  PHRASE_MEASURES,
} from "../config/tuning.js";
import { requireMinigame } from "../minigame/registry.js";
import type { AuthoredLevel } from "../minigame/api.js";
import type { EditorNote } from "./grid.js";
import { promptFromNotes } from "./prompt.js";
import type { LaneVocabulary } from "./vocabulary.js";

type Json = Record<string, unknown>;

/**
 * The provisional star ladder every scenario in the repository uses.
 *
 * Not a design decision made here — it is the ladder the `scripts/author-*.mjs`
 * tools baked into all seven scenarios, reproduced exactly so that re-saving an
 * untouched level changes nothing. Three stars is every opportunity in the
 * attempt taken at Perfect (GDD §7). The pass bar is deliberately **not** scaled
 * by the repeat: it stays 45% of what a single clean pass is worth, so a good
 * second pass redeems a bad first read, which is the whole reason an attempt
 * plays the phrase twice (`src/config/tuning.ts` ATTEMPT_REPEATS).
 */
const PASS_SHARE_OF_ONE_PASS = 0.45;
const STAR2_SHARE_OF_ATTEMPT = 0.8;

export type StarLadder = {
  passThreshold: number;
  star2Threshold: number;
  star3Threshold: number;
};

export function starLadder(noteOpportunityCount: number): StarLadder {
  const onePass = noteOpportunityCount * JUDGMENT_POINTS.perfect;
  const attempt = onePass * ATTEMPT_REPEATS;
  return {
    passThreshold: Math.round(onePass * PASS_SHARE_OF_ONE_PASS),
    star2Threshold: Math.round(attempt * STAR2_SHARE_OF_ATTEMPT),
    star3Threshold: attempt,
  };
}

function starsBlock(existing: unknown, noteOpportunityCount: number): Json {
  const was = (existing ?? {}) as Json;
  const ladder = starLadder(noteOpportunityCount);
  const unchanged =
    was["passThreshold"] === ladder.passThreshold &&
    was["star2Threshold"] === ladder.star2Threshold &&
    was["star3Threshold"] === ladder.star3Threshold;

  // The prose is kept while the numbers hold: it is the designer's, and it says
  // more about the level than a generated sentence could. Once the numbers move
  // it would be describing thresholds that no longer exist.
  if (unchanged) return { ...was, ...ladder };
  return {
    metric: "judgmentPoints",
    metricNote:
      "Cumulative judgment points during the attempt: Perfect 10, Good 6, Miss 0 " +
      "(src/config/tuning.ts JUDGMENT_POINTS). Thresholds are cumulative and lock once earned.",
    ...was,
    ...ladder,
    provisional: true,
    note:
      `PROVISIONAL, generated by the minigame editor. An attempt plays this ` +
      `${PHRASE_MEASURES}-measure phrase ${ATTEMPT_REPEATS} times, so ` +
      `${ladder.star3Threshold} points are available. Pass is ${Math.round(PASS_SHARE_OF_ONE_PASS * 100)}% ` +
      `of a single clean pass and is deliberately NOT scaled by the repeat, so getting the phrase ` +
      `right the second time round redeems a bad first read. Two stars is ` +
      `${Math.round(STAR2_SHARE_OF_ATTEMPT * 100)}% and three stars 100% of the full attempt, so ` +
      `three stars still requires every note opportunity taken at Perfect.`,
  };
}

export type LevelBuild = {
  /** The authored level, or null when the timeline could not be written down. */
  readonly level: AuthoredLevel | null;
  readonly noteOpportunityCount: number;
  readonly problems: readonly string[];
};

/**
 * Builds one authored level from the timeline.
 *
 * `existing` is the level as it stands in the file, or null for a difficulty
 * this scenario has never authored. Either way the minigame gets the last word
 * on its own half.
 */
export function buildLevel(options: {
  existing: AuthoredLevel | null;
  difficulty: number;
  minigameId: string;
  notes: readonly EditorNote[];
  loopMeasures: number;
  vocabulary: LaneVocabulary;
}): LevelBuild {
  const { existing, difficulty, minigameId, notes, loopMeasures, vocabulary } = options;
  const prompt = promptFromNotes(notes, loopMeasures, vocabulary);
  const noteOpportunityCount = prompt.noteStartBeats.length;
  if (prompt.problems.length > 0) {
    return { level: null, noteOpportunityCount, problems: prompt.problems };
  }
  if (noteOpportunityCount === 0) {
    return {
      level: null,
      noteOpportunityCount,
      problems: ["this level has no notes — an attempt with no opportunities cannot be judged"],
    };
  }

  const was = (existing ?? {}) as Json;
  const measurePlan = (was["measurePlan"] ?? {}) as Json;
  const level: Json = {
    ...was,
    difficulty,
    supported: true,
    measurePlan: {
      ...measurePlan,
      attemptMeasures: PHRASE_MEASURES,
      beatsPerMeasure: BEATS_PER_MEASURE,
    },
    prompt: prompt.events,
    noteOpportunityCount,
    authoredBeatCount: PHRASE_BEATS,
    stars: starsBlock(was["stars"], noteOpportunityCount),
    scoring: (was["scoring"] as Json) ?? { streakBonusEligible: false },
    validation: { status: "ok", issues: [] },
  };

  const minigame = requireMinigame(minigameId, "the minigame editor");
  const reconciled = minigame.authoring
    ? minigame.authoring.reconcileLevel(level, {
        difficulty,
        noteOpportunityCount,
        measures: PHRASE_MEASURES,
        attemptRepeats: ATTEMPT_REPEATS,
        noteStartBeats: prompt.noteStartBeats,
      })
    : level;

  return { level: reconciled, noteOpportunityCount, problems: [] };
}

/**
 * Puts a level into a scenario file, adding it to `supportedLevels` if it is new.
 *
 * Returns a fresh object; the editor never mutates the file it read.
 */
export function withLevel(raw: unknown, difficulty: number, level: AuthoredLevel): Json {
  const scenario = { ...((raw ?? {}) as Json) };
  const levels = { ...((scenario["levels"] ?? {}) as Json) };
  levels[String(difficulty)] = level;

  const supported = Array.isArray(scenario["supportedLevels"])
    ? scenario["supportedLevels"].filter((entry): entry is number => typeof entry === "number")
    : [];
  if (!supported.includes(difficulty)) supported.push(difficulty);

  scenario["levels"] = levels;
  scenario["supportedLevels"] = [...supported].sort((a, b) => a - b);
  return scenario;
}

/** Removes a level. Returns null when it was the scenario's last one. */
export function withoutLevel(raw: unknown, difficulty: number): Json | null {
  const scenario = { ...((raw ?? {}) as Json) };
  const levels = { ...((scenario["levels"] ?? {}) as Json) };
  delete levels[String(difficulty)];
  if (Object.keys(levels).length === 0) return null;

  scenario["levels"] = levels;
  scenario["supportedLevels"] = (
    Array.isArray(scenario["supportedLevels"]) ? scenario["supportedLevels"] : []
  ).filter((entry) => entry !== difficulty);
  return scenario;
}
